site_name: Bilingual Speech Recognition Docs
site_url: https://swp-team20.github.io/Bilingual-speech-recognition/
repo_url: https://github.com/SWP-Team20/Bilingual-speech-recognition

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

# Makes Mermaid more readable
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

# Site structure
nav:
  - Home: index.md
  - Development : deployment.md
  - Development Process: development-process.md
  - Definition of Done: definition-of-done.md
  - DB Scheme for team : db_schema_for_team.md
  - Quality Requirements : quality-requirements.md
  - Quality Requirements Tests : quality-requirements-tests.md
  - Roadmap : roadmap.md
  - RU/TT pipeline : ru_tt_pipeline.md
  - Storage and Search : storage_and_search.md
  - Testing : testing.md
  - User Acceptance Tests: user-acceptance-tests.md
  - User Stories : user-stories.md
  - Changelog : CHANGELOG.md
