site_name: Bilingual Speech Recognition Docs
site_url: https://swp-team20.github.io/Bilingual-speech-recognition/
repo_url: https://github.com/SWP-Team20/Bilingual-speech-recognition

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - search

# Makes Mermaid more readable
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

# Site structure
nav:
  - Home: index.md
  - Setup & Deployment : deployment.md
  - Development Process: development-process.md
  - Roadmap : roadmap.md
  - Definition of Done: definition-of-done.md
  - User Stories : user-stories.md
  - Testing : testing.md
  - Quality Requirements : quality-requirements.md
  - Quality Requirements Tests : quality-requirements-tests.md
  - User Acceptance Tests: user-acceptance-tests.md
  - Customer Handover: customer-handover.md
  - Storage and Search: storage_and_search.md
  - RU/TT Pipeline: ru_tt_pipeline.md
  - Database Schema: db_schema_for_team.md
  - ASR Training Guide: asr_training_guide.md
  - Architecture:
      - Overview: architecture/README.md
      - Static View: architecture/static-view/static.md
      - Dynamic View: architecture/dynamic-view/dynamic.md
      - Deployment View: architecture/deployment-view/deployment.md
      - ADR-001 Audio Confidentiality: architecture/adr/ADR-001-audio-confidentiality.md
      - ADR-002 Frontend Build Quality: architecture/adr/ADR-002-frontend-build-quality.md
      - ADR-003 Pull Request Compliance: architecture/adr/ADR-003-pull-request-compliance.md
